"use client";

import { useEffect, useRef, useState } from "react";
import { BarChart3, Sparkles, Trophy } from "lucide-react";

type Snapshot = { title: string; leaderboard: { name: string; score: number }[]; poll: { question: string; total: number; options: { text: string; votes: number; percent: number }[] } | null; raffleNames: string[]; winner: { id: number; name: string; drawnAt: string } | null };

export function StageDashboard({ locale }: { locale: string }) {
  const [snapshot, setSnapshot] = useState<Snapshot | null>(null);
  const [winnerDisplay, setWinnerDisplay] = useState<string | null>(null);
  const [mixing, setMixing] = useState(false);
  const winnerId = useRef<number | null>(null);
  const en = locale === "en";

  useEffect(() => { let mounted = true; let shuffleTimer: number | undefined; let finishTimer: number | undefined; async function refresh() { const response = await fetch("/api/event-mode/stage", { cache: "no-store" }); if (!response.ok || !mounted) return; const data = await response.json() as { session: Snapshot | null }; if (!data.session) { setSnapshot(null); return; } setSnapshot(data.session); const nextWinner = data.session.winner; if (nextWinner && nextWinner.id !== winnerId.current) { winnerId.current = nextWinner.id; const names = data.session.raffleNames.length ? data.session.raffleNames : [nextWinner.name]; let index = 0; setMixing(true); shuffleTimer = window.setInterval(() => { setWinnerDisplay(names[index % names.length]); index += 1; }, 90); finishTimer = window.setTimeout(() => { if (shuffleTimer) window.clearInterval(shuffleTimer); setWinnerDisplay(nextWinner.name); setMixing(false); }, 1900); } } void refresh(); const polling = window.setInterval(refresh, 3000); return () => { mounted = false; window.clearInterval(polling); if (shuffleTimer) window.clearInterval(shuffleTimer); if (finishTimer) window.clearTimeout(finishTimer); }; }, []);

  if (!snapshot) return <main className="flex min-h-screen items-center justify-center bg-primary-950 p-10 text-center text-white"><div><Sparkles className="mx-auto size-16 text-accent" /><h1 className="mt-6 font-heading text-5xl font-bold">{en ? "Waiting for the live event" : "Canlı etkinlik bekleniyor"}</h1></div></main>;
  return <main className="min-h-screen bg-[radial-gradient(circle_at_top_right,rgba(232,93,44,.22),transparent_30%),#0b1230] p-6 text-white sm:p-10"><header className="mx-auto max-w-[100rem] text-center"><p className="text-sm font-bold uppercase tracking-[.24em] text-accent-200">Galata KGK</p><h1 className="mt-3 font-heading text-4xl font-bold sm:text-6xl">{snapshot.title}</h1></header>
    {winnerDisplay ? <section className={`mx-auto mt-8 max-w-5xl rounded-[2rem] border border-accent/40 bg-accent/15 p-8 text-center shadow-[0_0_80px_rgba(232,93,44,.2)] ${mixing ? "event-winner-mixing" : ""}`}><Trophy className="mx-auto size-12 text-accent-200" /><p className="mt-3 text-sm font-bold uppercase tracking-[.2em] text-accent-100">{mixing ? (en ? "Drawing..." : "Kazanan seçiliyor...") : (en ? "Winner" : "Kazanan")}</p><p className="mt-4 font-heading text-5xl font-bold sm:text-7xl">{winnerDisplay}</p></section> : null}
    <div className="mx-auto mt-8 grid max-w-[100rem] gap-7 lg:grid-cols-2"><section className="rounded-[2rem] border border-white/10 bg-white/[.06] p-6 backdrop-blur sm:p-8"><h2 className="flex items-center gap-3 font-heading text-3xl font-bold"><Trophy className="text-accent-200" />{en ? "Quiz leaderboard" : "Quiz skor tablosu"}</h2><div className="mt-6 space-y-3">{snapshot.leaderboard.slice(0, 10).map((entry, index) => <div key={`${entry.name}-${index}`} className="flex items-center gap-4 rounded-2xl bg-white/[.07] px-5 py-4 text-xl"><span className="flex size-10 items-center justify-center rounded-full bg-accent font-bold">{index + 1}</span><span className="flex-1 truncate font-semibold">{entry.name}</span><span className="font-heading text-2xl font-bold text-accent-100">{entry.score}</span></div>)}{!snapshot.leaderboard.length ? <p className="py-10 text-center text-white/60">{en ? "No scores yet" : "Henüz skor yok"}</p> : null}</div></section>
      <section className="rounded-[2rem] border border-white/10 bg-white/[.06] p-6 backdrop-blur sm:p-8"><h2 className="flex items-center gap-3 font-heading text-3xl font-bold"><BarChart3 className="text-accent-200" />{snapshot.poll?.question ?? (en ? "Live poll" : "Canlı anket")}</h2><div className="mt-7 space-y-6">{snapshot.poll?.options.map((option) => <div key={option.text}><div className="flex justify-between gap-3 text-lg font-semibold"><span>{option.text}</span><span>%{option.percent}</span></div><div className="mt-2 h-5 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-gradient-to-r from-primary-300 to-accent transition-[transform]" style={{ width: `${option.percent}%` }} /></div></div>)}{!snapshot.poll ? <p className="py-10 text-center text-white/60">{en ? "No active poll" : "Aktif anket yok"}</p> : null}</div></section></div>
  </main>;
}
