import Link from "next/link";
import { notFound } from "next/navigation";
import { requireAdmin } from "@/lib/admin-auth";
import { prisma } from "@/lib/prisma";
import { PositionApplicationStatus } from "@/lib/generated/prisma/client";
import { saveApplicationReviewAction, deletePositionApplicationAction } from "@/app/admin/(panel)/alim/actions";
import { ConfirmSubmitButton } from "@/components/admin/confirm-submit-button";

export const dynamic = "force-dynamic";
export default async function ApplicationDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ error?: string }> }) {
  await requireAdmin(); const { id } = await params; const { error } = await searchParams;
  const application = await prisma.positionApplication.findUnique({ where: { id: Number(id) }, include: { position: { select: { title: true } }, answers: { orderBy: [{ order: "asc" }, { id: "asc" }], include: { files: true } } } });
  if (!application) notFound();
  return <main><Link href="/admin/alim/basvurular" className="text-accent-700 underline dark:text-accent-300">← Başvurular</Link><h1 className="mt-4 font-heading text-3xl font-bold">{application.fullName}</h1><p className="mt-2 text-muted-foreground">{application.position.title} · {application.createdAt.toLocaleString("tr-TR")}</p>{error ? <p role="alert" className="mt-4 text-red-700 dark:text-red-300">{error}</p> : null}<section className="mt-7 grid gap-3 rounded-xl border border-primary/15 p-5 dark:border-white/15 sm:grid-cols-2"><p><b>Öğrenci no:</b> {application.studentNumber}</p><p><b>Telefon:</b> {application.phone}</p><p><b>E-posta:</b> {application.email}</p><p><b>Bölüm:</b> {application.departmentName}</p><p><b>Sınıf:</b> {application.classYear}</p><p><b>KVKK onayı:</b> {application.consentAcceptedAt.toLocaleString("tr-TR")}</p></section><section className="mt-8 space-y-4"><h2 className="font-heading text-2xl font-bold">Yanıtlar</h2>{application.answers.map((answer) => <article key={answer.id} className="rounded-xl border border-primary/15 p-5 dark:border-white/15"><h3 className="font-semibold">{answer.questionLabel}</h3><p className="mt-3 whitespace-pre-wrap text-muted-foreground">{answer.boolValue === null ? answer.textValue || "—" : answer.boolValue ? "Evet" : "Hayır"}</p>{answer.files.map((file) => <a key={file.id} href={`/api/admin/join/files/${file.id}`} className="mt-3 block font-bold text-accent-700 underline dark:text-accent-300">{file.originalName} dosyasını indir ({Math.round(file.sizeBytes / 1024)} KB)</a>)}</article>)}</section><form action={saveApplicationReviewAction} className="mt-8 grid gap-3 rounded-xl border border-primary/15 p-5 dark:border-white/15"><input type="hidden" name="id" value={application.id} /><h2 className="font-heading text-xl font-bold">Değerlendirme</h2><label>Durum<select name="status" defaultValue={application.status} className="mt-1 block rounded-lg border p-2 text-primary-950">{Object.values(PositionApplicationStatus).map((status) => <option key={status}>{status}</option>)}</select></label><label>Yönetici notu<textarea name="adminNote" defaultValue={application.adminNote || ""} rows={5} maxLength={10000} className="mt-1 block w-full rounded-lg border p-2 text-primary-950" /></label><button className="justify-self-start rounded-lg bg-accent px-4 py-2 font-bold text-primary-950">Kaydet</button></form><form action={deletePositionApplicationAction} className="mt-8"><input type="hidden" name="id" value={application.id} /><ConfirmSubmitButton message="Başvuru ve özel dosyaları kalıcı olarak silinsin mi?">Başvuruyu ve dosyaları kalıcı sil</ConfirmSubmitButton></form></main>;
}
