import Link from "next/link";
import { requireAdmin } from "@/lib/admin-auth";
import { prisma } from "@/lib/prisma";
import { PositionApplicationStatus } from "@/lib/generated/prisma/client";

export const dynamic = "force-dynamic";
export default async function ApplicationsPage({ searchParams }: { searchParams: Promise<{ positionId?: string; status?: string; q?: string; page?: string }> }) {
  await requireAdmin(); const params = await searchParams;
  const positionId = Number(params.positionId) || undefined;
  const status = Object.values(PositionApplicationStatus).includes(params.status as PositionApplicationStatus) ? params.status as PositionApplicationStatus : undefined;
  const q = (params.q || "").trim().slice(0, 100); const page = Math.max(1, Number(params.page) || 1); const take = 25;
  const where = { ...(positionId ? { positionId } : {}), ...(status ? { status } : {}), ...(q ? { OR: [{ fullName: { contains: q, mode: "insensitive" as const } }, { studentNumber: { contains: q } }, { email: { contains: q, mode: "insensitive" as const } }] } : {}) };
  const [applications, count, positions] = await Promise.all([prisma.positionApplication.findMany({ where, orderBy: { createdAt: "desc" }, skip: (page - 1) * take, take, include: { position: { select: { title: true } } } }), prisma.positionApplication.count({ where }), prisma.recruitmentPosition.findMany({ orderBy: { order: "asc" }, select: { id: true, title: true } })]);
  return <main><h1 className="font-heading text-3xl font-bold">Saha Ekibi Başvuruları</h1><p className="mt-2 text-muted-foreground">Toplam {count} başvuru.</p><form className="mt-6 flex flex-wrap gap-3"><input name="q" defaultValue={q} placeholder="Ad, no veya e-posta" className="rounded-lg border p-2 text-primary-950" /><select name="positionId" defaultValue={positionId || ""} className="rounded-lg border p-2 text-primary-950"><option value="">Tüm pozisyonlar</option>{positions.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select><select name="status" defaultValue={status || ""} className="rounded-lg border p-2 text-primary-950"><option value="">Tüm durumlar</option>{Object.values(PositionApplicationStatus).map((item) => <option key={item}>{item}</option>)}</select><button className="rounded-lg bg-accent px-4 py-2 font-bold text-primary-950">Filtrele</button><a href={`/api/admin/join/applications.csv?${new URLSearchParams({ positionId: positionId?.toString() || "", status: status || "", q })}`} className="rounded-lg border px-4 py-2">CSV indir</a></form><div className="mt-7 space-y-3">{applications.map((application) => <Link key={application.id} href={`/admin/alim/basvurular/${application.id}`} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-primary/15 bg-card p-5 hover:border-accent-600 dark:border-white/15"><div><p className="font-bold">{application.fullName}</p><p className="mt-1 text-sm text-muted-foreground">{application.position.title} · {application.studentNumber} · {application.email}</p></div><div className="text-sm"><span className="font-bold">{application.status}</span><p>{application.createdAt.toLocaleDateString("tr-TR")}</p></div></Link>)}</div><div className="mt-5 flex gap-4">{page > 1 ? <Link href={`/admin/alim/basvurular?${new URLSearchParams({ ...params, page: String(page - 1) })}`}>← Önceki</Link> : null}{page * take < count ? <Link href={`/admin/alim/basvurular?${new URLSearchParams({ ...params, page: String(page + 1) })}`}>Sonraki →</Link> : null}</div></main>;
}
