import Link from "next/link";
import { requireAdmin } from "@/lib/admin-auth";
import { prisma } from "@/lib/prisma";
import { savePositionAction } from "@/app/admin/(panel)/alim/actions";

export const dynamic = "force-dynamic";
export default async function PositionsPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  await requireAdmin(); const { error } = await searchParams;
  const positions = await prisma.recruitmentPosition.findMany({ orderBy: [{ order: "asc" }, { id: "asc" }], include: { _count: { select: { applications: true } } } });
  return <main><h1 className="font-heading text-3xl font-bold">Saha Ekibi Alımı · Pozisyonlar</h1><p className="mt-2 text-muted-foreground">Pozisyonlar kapalı başlar. Önce içeriği ve soruları kontrol edip sonra açın.</p>{error ? <p role="alert" className="mt-4 text-red-700 dark:text-red-300">{error}</p> : null}<div className="mt-7 grid gap-4 lg:grid-cols-2">{positions.map((position) => <article key={position.id} className="rounded-xl border border-primary/15 bg-card p-5 dark:border-white/15"><div className="flex items-start justify-between gap-3"><h2 className="font-heading text-xl font-bold">{position.title}</h2><span className={`rounded-full px-3 py-1 text-xs font-bold ${position.isArchived ? "bg-slate-200 text-slate-900" : position.isOpen ? "bg-emerald-100 text-emerald-900" : "bg-amber-100 text-amber-900"}`}>{position.isArchived ? "Arşiv" : position.isOpen ? "Açık" : "Kapalı"}</span></div><p className="mt-2 text-sm text-muted-foreground">{position.shortDescription}</p><p className="mt-4 text-sm">{position._count.applications} başvuru / {position.quota ?? "Sınırsız"} kontenjan</p><p className="mt-1 text-sm">Son tarih: {position.deadline ? position.deadline.toLocaleString("tr-TR", { timeZone: "Europe/Istanbul" }) : "Yok"}</p><Link href={`/admin/alim/pozisyonlar/${position.id}`} className="mt-5 inline-block font-bold text-accent-700 underline dark:text-accent-300">Düzenle →</Link></article>)}</div><form action={savePositionAction} className="mt-8 grid gap-3 rounded-xl border border-dashed p-5"><h2 className="font-heading text-xl font-bold">Yeni pozisyon</h2><input name="title" required placeholder="Pozisyon adı" className="rounded-lg border p-2 text-primary-950" /><input name="slug" placeholder="slug (boşsa otomatik)" className="rounded-lg border p-2 text-primary-950" /><input name="shortDescription" required minLength={10} placeholder="Kısa açıklama" className="rounded-lg border p-2 text-primary-950" /><textarea name="detailMarkdown" required minLength={10} placeholder="Detay (Markdown)" rows={5} className="rounded-lg border p-2 text-primary-950" /><label>Sıra <input name="order" type="number" min="0" defaultValue={positions.length + 1} className="w-24 rounded-lg border p-2 text-primary-950" /></label><button className="justify-self-start rounded-lg bg-accent px-5 py-2 font-bold text-primary-950">Kapalı oluştur</button></form></main>;
}
