import { requireAdmin } from "@/lib/admin-auth";
import { prisma } from "@/lib/prisma";
import { deleteClubMemberAction } from "@/app/admin/(panel)/alim/actions";
import Link from "next/link";
import { ConfirmSubmitButton } from "@/components/admin/confirm-submit-button";

export const dynamic = "force-dynamic";
export default async function ClubMembersPage({ searchParams }: { searchParams: Promise<{ q?: string; department?: string; year?: string; page?: string }> }) {
  await requireAdmin();
  const params = await searchParams; const q = (params.q || "").trim().slice(0, 100); const page = Math.max(1, Number(params.page) || 1); const take = 25;
  const where = { ...(q ? { OR: [{ fullName: { contains: q, mode: "insensitive" as const } }, { studentNumber: { contains: q } }, { email: { contains: q, mode: "insensitive" as const } }] } : {}), ...(params.department ? { departmentName: params.department } : {}), ...(params.year ? { classYear: params.year } : {}) };
  const [members, count, departments] = await Promise.all([prisma.clubMember.findMany({ where, orderBy: { createdAt: "desc" }, skip: (page - 1) * take, take }), prisma.clubMember.count({ where }), prisma.department.findMany({ orderBy: { order: "asc" }, select: { name: true } })]);
  return <main><h1 className="font-heading text-3xl font-bold">Kulüp Üyeleri</h1><p className="mt-2 text-muted-foreground">Toplam {count} kayıt. Bu liste saha ekibi başvurularından bağımsızdır.</p><form className="mt-6 flex flex-wrap gap-3"><input name="q" defaultValue={q} placeholder="Ad, no veya e-posta" className="rounded-lg border p-2 text-primary-950" /><select name="department" defaultValue={params.department || ""} className="rounded-lg border p-2 text-primary-950"><option value="">Tüm bölümler</option>{departments.map((item) => <option key={item.name}>{item.name}</option>)}</select><select name="year" defaultValue={params.year || ""} className="rounded-lg border p-2 text-primary-950"><option value="">Tüm sınıflar</option>{["Hazırlık", "1", "2", "3", "4", "5"].map((year) => <option key={year}>{year}</option>)}</select><button className="rounded-lg bg-accent px-4 py-2 font-bold text-primary-950">Filtrele</button><a className="rounded-lg border px-4 py-2" href={`/api/admin/join/members.csv?${new URLSearchParams({ q, department: params.department || "", year: params.year || "" })}`}>CSV indir</a></form><div className="mt-6 overflow-x-auto rounded-xl border border-primary/15 dark:border-white/15"><table className="w-full min-w-[800px] text-left text-sm"><thead className="bg-primary/5 dark:bg-white/5"><tr>{["Ad Soyad", "Öğrenci No", "E-posta", "Telefon", "Bölüm / Sınıf", "Tarih", ""].map((name) => <th key={name} className="p-3">{name}</th>)}</tr></thead><tbody>{members.map((member) => <tr key={member.id} className="border-t border-primary/10 dark:border-white/10"><td className="p-3 font-semibold">{member.fullName}</td><td className="p-3">{member.studentNumber}</td><td className="p-3">{member.email}</td><td className="p-3">{member.phone}</td><td className="p-3">{member.departmentName} / {member.classYear}</td><td className="p-3">{member.createdAt.toLocaleDateString("tr-TR")}</td><td className="p-3"><form action={deleteClubMemberAction}><input type="hidden" name="id" value={member.id} /><ConfirmSubmitButton message={`${member.fullName} kaydı kalıcı olarak silinsin mi?`}>Sil</ConfirmSubmitButton></form></td></tr>)}</tbody></table></div><div className="mt-5 flex gap-4">{page > 1 ? <Link href={`/admin/kulup-uyeleri?${new URLSearchParams({ ...params, page: String(page - 1) })}`}>← Önceki</Link> : null}{page * take < count ? <Link href={`/admin/kulup-uyeleri?${new URLSearchParams({ ...params, page: String(page + 1) })}`}>Sonraki →</Link> : null}</div></main>;
}
